services:
  commande-service:
    build: .
    ports:
      - "${COMMANDE_PORT}:3000"
    command: npm run start
    depends_on:
      service-bdd-mysql:
        condition: service_healthy
    env_file:
      - .env

  service-bdd-mysql:
    image: mysql:8.0
    container_name: bdd-commande-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_FORWARD_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p${DB_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  mysql_data: